parameters:
  - name: version
    displayName: Release Version (e.g. v0.1.0)
    type: string
  - name: artifactBuildId
    displayName: "Artifact source build id (defaults uses this build)"
    type: number
    default: 0

variables:
  - name: pipelineId
    value: 191

stages:
  - stage: build
    pool:
      name: pool-ubuntu-2004
    displayName: "Build azapi-lsp"
    jobs:
      - job: build
        displayName: "Build Binaries"
        strategy:
          matrix:
            windows-386:
              OS: windows
              ARCH: 386
            windows-amd64:
              OS: windows
              ARCH: amd64
            windows-arm64:
              OS: windows
              ARCH: arm64
            linux-amd64:
              OS: linux
              ARCH: amd64
            linux-arm:
              OS: linux
              ARCH: arm
            linux-arm64:
              OS: linux
              ARCH: arm64
            darwin-amd64:
              OS: darwin
              ARCH: amd64
            darwin-arm64:
              OS: darwin
              ARCH: arm64
        steps:
          - task: GoTool@0
            displayName: "Install Go"
            inputs:
              version: 1.19
          - script: |
              set -e
              mkdir build
              name=azapi-lsp
              if [[ $OS = windows ]]; then
                  name=azapi-lsp.exe
              fi
              GOOS="${OS}" GOARCH="${ARCH}" CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X 'main.version=${VERSION}'" -o build/$name
            displayName: "Go Build"
            env:
              OS: $(OS)
              ARCH: $(ARCH)
              VERSION: ${{ parameters.version }}
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '3.x'
          - task: EsrpCodeSigning@1
            displayName: "Sign Binary (Windows Only)"
            condition: eq(variables.OS, 'windows')
            inputs:
              ConnectedServiceName: "ESRP Signing Service"
              FolderPath: "$(system.defaultWorkingDirectory)/build"
              Pattern: "*.exe"
              signConfigType: "inlineSignParams"
              inlineOperation: |
                [
                        {
                            "KeyCode" : "CP-230012",
                            "OperationCode" : "SigntoolSign",
                            "Parameters" : {
                                "OpusName" : "Microsoft",
                                "OpusInfo" : "http://www.microsoft.com",
                                "PageHash" : "/NPH",
                                "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256",
                                "FileDigest": "/fd \"SHA256\""
                            },
                            "ToolName" : "sign",
                            "ToolVersion" : "1.0"
                        },
                        {
                            "KeyCode" : "CP-230012",
                            "OperationCode" : "SigntoolVerify",
                            "Parameters" : {},
                            "ToolName" : "sign",
                            "ToolVersion" : "1.0"
                        }
                ]
              SessionTimeout: "60"
              MaxConcurrency: "50"
              MaxRetryAttempts: "5"
          - task: PublishPipelineArtifact@1
            displayName: "Publish Binary"
            inputs:
              targetPath: "$(system.defaultWorkingDirectory)/build"
              artifactName: "$(OS)-$(ARCH)"

  - stage: github_release
    displayName: "Github Draft Release"
    pool:
      name: pool-ubuntu-2004
    jobs:
      - job: release
        displayName: "Github Release"
        steps:
          - ${{ if eq(parameters.artifactBuildId, 0) }}:
            - task: DownloadPipelineArtifact@2
              inputs:
                path: $(system.defaultWorkingDirectory)/dist
          - ${{ else }}:
            - task: DownloadPipelineArtifact@2
              inputs:
                path: $(system.defaultWorkingDirectory)/dist
                source: "specific"
                project: "release"
                pipeline: $(pipelineId)
                runVersion: "specific"
                runId: ${{ parameters.artifactBuildId }}
          - script: |
              set -e
              NAME="azapi-lsp"
              OS_ARCH=(
                "windows:amd64"
                "windows:arm64"
                "windows:386"
                "linux:amd64"
                "linux:arm"
                "linux:arm64"
                "darwin:amd64"
                "darwin:arm64"
              )
              mkdir release
              for os_arch in "${OS_ARCH[@]}" ; do
                OS=${os_arch%%:*}
                ARCH=${os_arch#*:}
                name=azapi-lsp
                if [[ $OS = windows ]]; then
                    name=azapi-lsp.exe
                fi
                chmod +x dist/${OS}-${ARCH}/${name}
                zip -j release/${NAME}_${VERSION}_${OS}_${ARCH}.zip dist/${OS}-${ARCH}/${name}
              done

              cd release
              shasum -a 256 *.zip > ${NAME}_SHA256SUMS
              cp ${NAME}_SHA256SUMS ${NAME}_SHA256SUMS.sig
            displayName: "Prepare Binary Archives & Digests"
            env:
              VERSION: ${{ parameters.version }}
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '3.x'
          - task: EsrpCodeSigning@1
            displayName: "Sign Binary Archive Digests"
            inputs:
              ConnectedServiceName: "ESRP Signing Service"
              FolderPath: "$(system.defaultWorkingDirectory)/release"
              Pattern: "*_SHA256SUMS.sig"
              signConfigType: "inlineSignParams"
              inlineOperation: |
                [
                  {
                      "KeyCode": "CP-450779-Pgp",
                      "OperationCode": "LinuxSign",
                      "Parameters": {},
                      "ToolName": "sign",
                      "ToolVersion": "1.0"
                  }
                ]
              SessionTimeout: "60"
              MaxConcurrency: "50"
              MaxRetryAttempts: "5"
          - task: GitHubRelease@1
            displayName: "Draft Github Release"
            inputs:
              gitHubConnection: 'azapi2azurerm'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'gitTag'
              tagPattern: '^v\d+\.\d+\.\d+'
              assets: '$(system.defaultWorkingDirectory)/release/*'
              isDraft: true
              addChangeLog: false
